import type { Metadata } from "next";
import "./globals.css";
import ProvidersComp from "@/components/providers";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-behavior" lang="en">
      <body className="body-font scroll-behavior">
        <ProvidersComp>{children}</ProvidersComp>
      </body>
    </html>
  );
}
